#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../purgecss/bin/purgecss.js" "$@"
  ret=$?
else 
   /opt/hostedtoolcache/node/14.15.4/x64/bin/node  "$basedir/../purgecss/bin/purgecss.js" "$@"
  ret=$?
fi
exit $ret
