header:
    title: Dr. Tara Burke
    text: Naturopathic Doctor
    text2: Thyroid & Adrenal \| Hormones \| Telemedicine
    text3: Scottsdale, Arizona
    button: Discovery Call
    buttonlink: "https://drtaraburke.com/book" # "#{section}" or "URL/page link"

services:
    title: "Highlighted Services"
    text: "We strive to provide optimal health and wellness for our patients through individualized care. We give each of our patients the highest level of attention and time to address their unique health care needs. Ethical and evidence based medicine is our top priority. Through these ideals, Dr. Burke will provide integrative medicine that goes beyond the boundaries of conventional medicine."
    section: services
    list:
      - title: "Thyroid Health"
        link: "thyroid-health"
        desc: "With the aid of lab testing, we can measure a baseline of your thyroid’s health and then create a plan to manage and improve your thyroid’s function. Check out this [video](https://www.youtube.com/watch?v=oo3oTNJ0DT0) to learn the basics!"
        icon: fas fa-plus-square #find more at https://fontawesome.com/icons
      - title: "Hormone Balancing"
        link: "hormone-balancing"
        desc: "Hormone imbalances are common but should not be considered normal! Dr. Burke will help guide you and offer the best options available to balance your hormones."
        icon: fas fa-balance-scale-right       
      - title: "Adrenal Support"
        link: "adrenal-support"
        desc: "Dr. Burke can discuss herbal supplementation and lifestyle changes to help rejuvenate your adrenals."
        icon: fas fa-medkit
      - title: "Digestive Health"
        link: "digestive-health"
        desc: "Digestive Health doesn’t always end in the gut itself. Hormones, stress, lifestyle can all impact the gastrointestinal system, this is why finding the root cause of digestive health is incredibly important. Dr. Burke works with her patients to take back control of their digestive health."
        icon: fas fa-diagnoses
      - title: "Women's Medicine"
        link: "womens-medicine"
        desc: "Diagnose and treat common women’s health issues through integrative methods and alternative treatments. Dr. Burke is here for her patients through all of life’s transitions."
        icon: fas fa-female
      - title: "Menopause Consult"
        link: "menopause-consult"
        desc: "Are you curious about what options are available to you for your menopausal symptoms? Are you looking for more information on bio-identical hormones or hormone replacement therapy? Or perhaps you are curious about non-hormonal options? Let Dr. Burke present all the options available to you!"
        icon: fas fa-comments

team:
    title: "Meet Dr. Burke"
    #text: "Licensed Naturopathic Doctor"
    subtext:  Dr. Tara Burke is a licensed Naturopathic Doctor in Scottsdale, Arizona. Dr. Burke’s primary focus is in women’s medicine and endocrinology, having received extensive training in thyroid health, adrenal health, and hormone balance after graduation from the Southwest College of Naturopathic Medicine. She spends time with her patients to identify their individual health goals and treat, not just the symptoms, but the whole person. She utilizes lifestyle, nutrition, supplementation, herbals, acupuncture, and when indicated, medications, to find a solution for each of her patients. Ethical, evidence-based medicine is her top priority. Dr. Burke is currently practicing at Blossom Wellness in North Scottsdale, Arizona near to the Grayhawk, DC Ranch, Desert Ridge, and Pinnacle Peak areas. [Click Here to Schedule](https://drtaraburke.com/book). 
    section: about
    people:
      - name: "Dr. Tara Burke"
        role: "Naturopathic Medical Doctor"
        image: assets/img/team/dr-tara-burke-nmd.webp
        alt: Scottsdale Naturopathic Doctor
        social:
          - url: https://www.facebook.com/drtaraburke?rel=noreferrer
            icon: "fab fa-facebook-f"
          - url: https://www.youtube.com/channel/UCrr_4UKW_A_fk-5kVoWsovQ?rel=noreferrer
            icon: "fab fa-youtube"
          - url: https://www.pinterest.com/drtaraburke/?rel=noreferrer
            icon: "fab fa-pinterest"
          - url: https://www.instagram.com/dr.taraburke/?rel=noreferrer
            icon: "fab fa-instagram"
faq:
  - question: What should I expect at my first appointment?
    answer: |
      <p>
      With your first one hour appointment, we are able to fully discuss and understand your past and present health concerns. 
      We will review your health goals, dietary intake, medical history, medications and supplements. In addition, we will go through any previous lab work and imaging. 
      After reviewing these items, sometimes additional lab work and imaging will be recommended to further asses your unique case. 
      At the end of the visit, you will be provided with an individualized treatment plan and encouraged to ask questions to help educate you on your path to wellness!
      </p>
    open: true
  - question: Do you accept insurance?
    answer: |
      <p>At this time we do not contract with insurance. We are better able to provide the services patients require with shorter wait times, longer and meaningful visits, and better patient care with a cash based model. </p>
      <p>While we are not “in network” with any insurance plans, you may be able to receive reimbursement directly from the insurance company. Please check with your insurance company in order to determine what they require. Many insurance companies will also cover much of the lab work our provider may order.</p>
      <p> Dr. Burke works with every budget to provide optimal care to her patients.<p>
  - question: What conditions do you treat?
    answer: |
      <p>Dr. Burke is well versed in a variety of health conditions and concerns. However, she has special interest in Thyroid, Adrenal, Hormonal Balancing, and Women's Medicine. Please see the service page for additional information.</p>
  - question: How many visists are required?
    answer: |
      <p>Naturopathic and Integrative medicine often takes time to provide complete wellness. Giving a generalized time frame is difficult as each patient and condition is different, this is what makes the naturopathic approach to medicine so unique. </p>
      <p>As a general rule you may start to feel improvements after the first visit but you should expect a few visits over 3 months to see significant changes.</p>
      <p>Remember, for many chronic conditions, you didn’t start feeling poorly overnight - it probably took days, months, or even years. The longer a conditions has been present, the longer it may take to heal.</p>
      <p>A better time frame can be established after your initial consultation based on your health concerns, health goals, and treatment plan.</p>
  - question: Can you prescribe medications and controlled substances? 
    answer: |
      <p>Yes, in the state of Arizona Naturopathic Doctors are able to prescribe medications.</p>
      <p>They can also acquire a DEA number and can prescribe Schedule III, IV and V controlled substances.</p>
  - question: How much does a visit cost?
    answer: |
      <p>15 min Discovery Calls (New Patients Only) to discuss your health goals and options - Complimentary</p>
      <p>New Patient Visit (60 min) - $230</p>
      <p>Established Patient Follow- Up (30 min) - $115</p>
      <p>Acupuncture New Patient (45 min) - $150</p>
      <p>Acupuncture Existing Patient (30min) - $75</p>
      <p>For additional services or questions please contact the office at (480) 702-1445. Please note if you have extensive health concerns or would like extra time we offer extended time slots at $75 for every additional 15min.</p>
  
contact:
    title: "Contact Blossom Wellness"
    text: "EXISTING PATIENTS: Please use Patient Portal for ANY messages."
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://www.facebook.com/drtaraburke?rel=noreferrer
        icon: "fab fa-facebook-f"
      - url: https://www.youtube.com/channel/UCrr_4UKW_A_fk-5kVoWsovQ?rel=noreferrer
        icon: "fab fa-youtube"
      - url: https://www.pinterest.com/drtaraburke/?rel=noreferrer
        icon: "fab fa-pinterest"
      - url: https://www.instagram.com/dr.taraburke/?rel=noreferrer
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
